# Generated by Django 4.2.5 on 2023-09-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_timeslot_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
    ]
