# Generated by Django 4.2.5 on 2023-09-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_timeslot_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'start_time')},
        ),
    ]
