# Generated by Django 4.2.5 on 2023-09-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_timeslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
