# Generated by Django 4.2.5 on 2023-09-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_timeslot_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='canceled',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='confirmed', max_length=10),
        ),
    ]
