# Generated by Django 4.2.5 on 2023-10-21 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_waitlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('start_time', 'date')},
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.timeslot'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
